### ISSUE TITLE
Variance linear output layer?

### ISSUE THREAD

**Issue by AlexanderKoch-Koch** [xbpeng/mcp#2]
Hi,
in the paper it says: "a linear output layer that produces μi(s) and Σi (s) for each primitive".
However, in the formula to calculate the resulting distribution you have to divide by the variance. So a zero variance would be a problem. And I don't know if a negative variance makes sense?

**Comment by xbpeng** [comment]
Right, the linear output layer actually outputs the log variance. We apply an exp to prevent non positive variance.
